# Generated by Django 5.2.11 on 2026-02-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('poll', 'text'), name='unique_option_per_poll'),
        ),
    ]
